'use strict';
(() => {
 const $=id=>document.getElementById(id);
 const labels={pose:{standing:'站立',crouching:'蹲姿',prone:'卧姿'},action:{ready:'就绪',reload:'换弹',inventory:'背包',grenade:'投掷',melee:'近战',heal:'治疗',sprint:'冲刺',dead:'死亡',vehicle:'载具'},ads:{ads:'开镜',hipfire:'腰射'},ammo:{empty:'空仓',nonempty:'非空仓'}};
 const reasonNames={CANDIDATE:'已找到候选',LOW_SIMILARITY:'未找到足够相似的图标',AMBIGUOUS_LABEL:'多个状态难以区分',AMBIGUOUS_LOCATION:'多个位置难以区分'};
 let token,refs=[],roi=null,refImage=null,queryImage=null,queryData=null,revision=0,timer=null,queryRevision=0,dragStart=null;
 const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 async function guard(fn){try{$('adaptive-message').textContent='';await fn();}catch(e){$('adaptive-message').textContent=e.message||String(e);}}
 function fileData(file){return new Promise((resolve,reject)=>{if(!file||file.size>6*1024*1024)return reject(Error('请选择不超过6 MiB的图片'));const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('读取失败'));r.readAsDataURL(file);});}
 function bitmap(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>image.width*image.height<=12000000?resolve(image):reject(Error('图片超过1200万像素'));image.onerror=()=>reject(Error('图片格式无效'));image.src=src;});}
 function draw(id,image,box){const c=$(id),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(!image)return;ctx.drawImage(image,0,0);if(box){ctx.strokeStyle='#72e1cb';ctx.lineWidth=Math.max(2,c.width/400);ctx.strokeRect(...box);}}
 function fit(id,image){const c=$(id);c.width=image.width;c.height=image.height;draw(id,image,null);}
 function ready(){return token&&roi&&refs.length>=2&&refs.every(r=>r.image)&&queryData&&$('adaptive-layout').value.trim();}
 function invalidate(){revision++;clearTimeout(timer);draw('query-canvas',queryImage,null);$('adaptive-status').textContent='输入已变化';$('adaptive-output').textContent='等待本轮分析，不沿用上次识别结果。';if($('adaptive-auto').checked&&ready())timer=setTimeout(()=>guard(analyze),250);}
 async function setReference(index,source,request){const r=refs[index];const image=await bitmap(source);if(refs[index]!==r||request!==r.request)return;r.image=source;if(index===0){refImage=image;roi=null;fit('reference-canvas',image);$('reference-size').textContent=`原图 ${image.width} × ${image.height}（自动读取）`;$('adaptive-roi').textContent='请在新参考图上框选一次图标。';}invalidate();}
 function addReference(data){if(refs.length>=8)return;const index=refs.length,entries=Object.entries(labels[$('adaptive-field').value]);const ref={label:data?.label||entries[Math.min(index,entries.length-1)][0],image:null,request:0};refs.push(ref);const row=node('label','参考状态 '),sel=node('select'),input=node('input');for(const [key,text]of entries){const o=node('option',text);o.value=key;sel.append(o);}sel.value=ref.label;input.type='file';input.accept='image/png,image/jpeg,image/webp';sel.onchange=()=>{ref.label=sel.value;invalidate();};input.onchange=()=>guard(async()=>{const request=++ref.request;invalidate();ref.image=null;const source=await fileData(input.files[0]);if(refs[index]!==ref||request!==ref.request)return;await setReference(index,source,request);});row.append(sel,input);$('adaptive-references').append(row);return ref;}
 function pack(){const layout=$('adaptive-layout').value.trim();if(!layout||!roi||!refs.every(r=>r.image))throw Error('请补齐布局标识、参考图和参考区域');return {schema_version:1,kind:'local_hud_reference_pack',field:$('adaptive-field').value,layout_id:layout,roi:roi.slice(),references:refs.map(r=>({label:r.label,image:r.image,layout_id:layout}))};}
 async function analyze(){if(!ready())throw Error('请先提供至少两种参考状态、框选一次图标，再选择待测图');const version=revision;const body={...pack(),image:queryData};$('adaptive-status').textContent='正在自动定位…';const response=await fetch('/api/hud-adaptive',{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':token},body:JSON.stringify(body)});const result=await response.json();if(version!==revision)return;if(!response.ok)throw Error(result.error||'分析失败');$('adaptive-status').textContent=result.label==='unknown'?'未知 / 需要确认':`候选：${labels[body.field][result.label]}`;$('adaptive-detail').textContent=`${reasonNames[result.reason]||result.reason}；相似度 ${result.score.toFixed(3)}；匹配比例 ${result.scale?.toFixed(3)||'—'}；${result.self_match?'同图自检，不是独立验证':'尚未经游戏实机验证'}`;$('adaptive-output').textContent=JSON.stringify(result,null,2);draw('query-canvas',queryImage,result.roi);}
 function point(e){const c=$('reference-canvas'),b=c.getBoundingClientRect();return [Math.max(0,Math.min(c.width,Math.round((e.clientX-b.left)*c.width/b.width))),Math.max(0,Math.min(c.height,Math.round((e.clientY-b.top)*c.height/b.height)))];}
 const canvas=$('reference-canvas');canvas.style.touchAction='none';
 canvas.onpointerdown=e=>{if(!refImage)return;dragStart=point(e);canvas.setPointerCapture(e.pointerId);};
 canvas.onpointermove=e=>{if(!dragStart)return;const p=point(e);draw('reference-canvas',refImage,[Math.min(p[0],dragStart[0]),Math.min(p[1],dragStart[1]),Math.abs(p[0]-dragStart[0]),Math.abs(p[1]-dragStart[1])]);};
 canvas.onpointerup=e=>{if(!dragStart)return;const p=point(e),box=[Math.min(p[0],dragStart[0]),Math.min(p[1],dragStart[1]),Math.abs(p[0]-dragStart[0]),Math.abs(p[1]-dragStart[1])];dragStart=null;if(box[2]<8||box[3]<8||box[2]>256||box[3]>256){$('adaptive-message').textContent='请框8～256像素宽高的稳定小图标';draw('reference-canvas',refImage,roi);return;}roi=box;draw('reference-canvas',refImage,roi);$('adaptive-roi').textContent=`原图 [${roi.join(', ')}]；目标坐标由程序查找`;invalidate();};
 canvas.onpointercancel=()=>{dragStart=null;draw('reference-canvas',refImage,roi);};
 $('adaptive-field').onchange=()=>{refs=[];roi=null;refImage=null;$('adaptive-references').replaceChildren();draw('reference-canvas',null,null);$('reference-size').textContent='请提供新字段参考图';addReference();addReference();invalidate();};
 $('adaptive-add').onclick=()=>{addReference();invalidate();};$('adaptive-layout').oninput=invalidate;$('adaptive-auto').onchange=invalidate;
 $('adaptive-query').onchange=()=>guard(async()=>{const request=++queryRevision;queryData=null;queryImage=null;invalidate();const source=await fileData($('adaptive-query').files[0]);const image=await bitmap(source);if(request!==queryRevision)return;queryData=source;queryImage=image;fit('query-canvas',image);$('query-size').textContent=`原图 ${image.width} × ${image.height}（自动读取）；不修改配装分辨率`;invalidate();});
 $('adaptive-run').onclick=()=>guard(analyze);
 $('adaptive-export').onclick=()=>guard(async()=>{const data=pack(),url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=node('a');a.href=url;a.download='local-hud-reference-pack.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 $('adaptive-import').onchange=()=>guard(async()=>{const file=$('adaptive-import').files[0];if(!file||file.size>32*1024*1024)throw Error('参考包最大32 MiB');const p=JSON.parse(await file.text());if(p.schema_version!==1||p.kind!=='local_hud_reference_pack'||!Object.hasOwn(labels,p.field)||typeof p.layout_id!=='string'||!Array.isArray(p.references)||p.references.length<2||p.references.length>8||!Array.isArray(p.roi)||p.roi.length!==4||!p.roi.every(Number.isInteger))throw Error('参考包结构无效');if(p.references.some(r=>!r||!Object.hasOwn(labels[p.field],r.label)||typeof r.image!=='string'||r.image.length>9*1024*1024||!r.image.startsWith('data:image/')))throw Error('参考图条目无效');const image=await bitmap(p.references[0].image);refs=[];$('adaptive-references').replaceChildren();$('adaptive-field').value=p.field;$('adaptive-layout').value=p.layout_id;for(const r of p.references){const ref=addReference(r);ref.image=r.image;}roi=p.roi.slice();refImage=image;fit('reference-canvas',image);draw('reference-canvas',image,roi);$('reference-size').textContent=`参考包 ${image.width} × ${image.height}；新图片无需相同尺寸`;$('adaptive-roi').textContent=`已载入原图区域 [${roi.join(', ')}]`;invalidate();});
 addReference();addReference();guard(async()=>{const r=await fetch('/api/bootstrap');if(!r.ok)throw Error('本地服务不可用');token=(await r.json()).token;});
})();
