'use strict';
(() => {
 const $ = id => document.getElementById(id);
 const scenarios={normal:'正常开镜连射',empty:'空仓立即停止',reload:'换弹不输出',grenade:'投掷不输出',inventory:'背包不输出',melee:'近战不输出',hipfire:'腰射不输出',unknown:'弹药状态未知',stale:'观察帧已过期',pose_change:'站姿切成蹲姿',switch:'切至未测量配装',semi:'半自动模式不套连射曲线',release:'短点射松开即停',heal:'治疗不输出',unfocus:'切出窗口',inference:'仅靠按键推断，未确认'};
 const labels={pose:{standing:'站立',crouching:'蹲姿',prone:'卧姿'},action:{ready:'就绪',reload:'换弹',inventory:'背包',grenade:'投掷',melee:'近战',heal:'治疗',sprint:'冲刺',dead:'死亡',vehicle:'载具'},ads:{ads:'开镜',hipfire:'腰射'},ammo:{empty:'空仓',nonempty:'非空仓'}};
 let token, report=null, image=null, revision=0, queryVersion=0;
 const node=(name,text)=>{const n=document.createElement(name);if(text!==undefined)n.textContent=text;return n;};
 async function api(path,body){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json','X-Lab-Token':token},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'请求失败');return d;}
 async function guard(fn){try{$('lab-message').textContent='';await fn();}catch(e){$('lab-message').textContent=e.message||String(e);}}
 function invalidate(){revision++;$('hud-output').textContent='输入已变化，请重新比较。';draw();}
 function addReference(){if($('references').children.length>=8)return;const row=node('label','参考图 ');const select=node('select');const entries=Object.entries(labels[$('hud-field').value]);for(const [value,text]of entries){const o=node('option',text);o.value=value;select.append(o);}select.selectedIndex=Math.min($('references').children.length,entries.length-1);const file=node('input');file.type='file';file.accept='image/png,image/jpeg,image/webp';select.onchange=file.onchange=invalidate;row.append(select,file);$('references').append(row);invalidate();}
 function loadFile(file){return new Promise((ok,no)=>{if(!file)return no(Error('请补齐图片'));if(file.size>6*1024*1024)return no(Error('每张图片最多6 MiB'));const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(Error('读取失败'));r.readAsDataURL(file);});}
 function roi(){return ['hud-x','hud-y','hud-w','hud-h'].map(id=>Number($(id).value));}
 function draw(){const c=$('hud-preview'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);if(image){ctx.drawImage(image,0,0);ctx.strokeStyle='#ffc65c';ctx.lineWidth=Math.max(2,c.width/500);ctx.strokeRect(...roi());}}
 function showState(r){report=r;$('export-state').disabled=false;const changes=r.trace.filter((row,i)=>i===0||row.reason!==r.trace[i-1].reason);$('state-output').textContent=changes.map(row=>`${row.t_s.toFixed(2)}s  ${row.reason}  |  记录事件 ${row.events_recorded}`).join('\n');$('state-summary').textContent=`${scenarios[r.scenario]}：${r.events.length} 条模拟事件；实机验证：未完成。`;
 const c=$('state-chart'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);ctx.font='16px sans-serif';const last=r.trace.at(-1).t_s;for(let i=0;i<r.trace.length;i++){const row=r.trace[i];ctx.fillStyle=row.eligible?'#72e1cb':'#5b6875';ctx.fillRect(20+row.t_s/last*950,38,12,55);}ctx.fillStyle='#dbe5ed';ctx.fillText('绿色：允许记录  /  灰色：停止或等待释放',20,24);for(const t of [0,.4,.8,1,1.6])ctx.fillText(t+'s',20+t/last*950,120);}
 async function compare(){const version=revision;const layout=$('hud-layout').value.trim();if(!layout)throw Error('请填写实际游戏版本和HUD布局标识');const references=await Promise.all([...$('references').children].map(async row=>({label:row.querySelector('select').value,layout_id:layout,image:await loadFile(row.querySelector('input').files[0])})));const q=await loadFile($('hud-query').files[0]);const body={field:$('hud-field').value,layout_id:layout,roi:roi(),threshold:Number($('hud-threshold').value),margin:Number($('hud-margin').value),references,image:q};const r=await api('/api/hud-compare',body);if(version!==revision)throw Error('输入已变化，丢弃过期结果');$('hud-output').textContent=JSON.stringify(r,null,2);}
 for(const [key,label]of Object.entries(scenarios)){const o=node('option',label);o.value=key;$('scenario').append(o);}
 $('run-state').onclick=()=>guard(async()=>{const scenario=$('scenario').value;const r=await api('/api/state-demo',{scenario});if($('scenario').value===scenario)showState(r);});
 $('scenario').onchange=()=>{report=null;$('export-state').disabled=true;$('state-output').textContent='场景已改变，请重新运行。';$('state-chart').getContext('2d').clearRect(0,0,1000,170);};
 $('export-state').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='synthetic-state-trace.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('hud-field').onchange=()=>{$('references').replaceChildren();addReference();addReference();};$('add-ref').onclick=addReference;
 for(const id of ['hud-layout','hud-x','hud-y','hud-w','hud-h','hud-threshold','hud-margin'])$(id).oninput=invalidate;
 $('hud-query').onchange=()=>guard(async()=>{invalidate();image=null;draw();const id=++queryVersion;const src=await loadFile($('hud-query').files[0]);const im=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=()=>no(Error('无法显示图片'));i.src=src;});if(id!==queryVersion)return;if(im.width*im.height>12000000)throw Error('图片超过1200万像素');image=im;const c=$('hud-preview');c.width=im.width;c.height=im.height;draw();});
 $('compare-hud').onclick=()=>guard(compare);addReference();addReference();
 guard(async()=>{const r=await fetch('/api/bootstrap');if(!r.ok)throw Error('本地服务连接失败');token=(await r.json()).token;showState(await api('/api/state-demo',{scenario:'normal'}));});
})();
